### ISSUE TITLE
Cannot generate grapqhl schema for Stripe API

### ISSUE THREAD

**Issue by ronanamsterdam** [IBM/openapi-to-graphql#197] opened 2019-07-09 07:17 UTC
**Describe the bug**
Not able to generate Graphql Schema with openapi-to-graphql cli using Stripe's API OAS definition

**To Reproduce**
1. install the openapi-to-graphql-cli
2. try generating schema by running:
`openapi-to-graphql https://api.apis.guru/v2/specs/stripe.com/2019-03-14/swagger.json`

**Expected behavior**
The graphql server starts with generated Stripe API schema

**Actual result**
Getting the following error:
```
openapi-to-graphql https://api.apis.guru/v2/specs/stripe.com/2019-03-14/swagger.json(node:54348) ExperimentalWarning: The http2 module is an experimental API.
OpenAPI-to-GraphQL creation event error:  Cannot read property 'schema' of null
```

**Additional context**
Up to date latest OAS Stripe's spec can be grabbed here:
https://github.com/stripe/openapi/blob/master/openapi/spec3.json
*same generation result as described above

**Comment by Alan-Cha** [comment] 2019-07-09 14:31
I can replicate this error. Will have a look!

**Comment by Alan-Cha** [comment] 2019-07-09 15:27
I found the problem. OAS uses a few [keywords](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) to combine schemas, namely "oneOf", "anyOf", "allOf", and "not". Currently OtG only supports "allOf". Stripe makes use of (at least) "anyOf". 

These keywords throw a wrench in the GraphQL ecosystem. Because GraphQL enforces a strong typing system and combining schemas muddles the typing. Implementing "allOf" is easy to do, but "oneOf" and "anyOf" are tricky, and "not" may be impossible (we will probably resort to stringifying the data or use the [GraphQL JSON type](https://github.com/taion/graphql-type-json)). For more information, see #14.

For the time being, I have improved reporting with #199.

**Comment by ronanamsterdam** [comment] 2019-07-10 02:21
Nice!) thanks for a swift reply!) we're looking forward to use the tool for out billing model, but currently blocked until this is resolved. Thank you for the effort 🙏

**Comment by Alan-Cha** [comment] 2019-07-10 05:06
I think I'll take a look at it later in the week! I experimented with a number of APIs on APIs.guru and a number of APIs used these keywords so it seems to be a common problem. Will report back!

**Comment by prevuelta** [comment] 2019-07-11 20:39
Objects defined with additionalProperties will also cause this error eg.
```
model: {
  type: "object",
  additionalProperties: { $ref: "...." }
}

**Comment by Disturbing** [comment] 2019-07-12 03:28
Thanks for looking into this issue quickly @Alan-Cha. We're looking to combine Stripe <> Hasura <> KintoHub and work together on creating easy-to-deploy swagger => graphql containers.

We can begin integration as soon as next week if things turn out positive on your end. Will be watching this thread closely :).

**Comment by tirumaraiselvan** [comment] 2019-07-12 07:18
@Alan-Cha Throwing few ideas here:

Can `oneOf` be equivalent to union type and `anyOf` be equivalent to an interface type?

**Comment by Alan-Cha** [comment] 2019-07-12 14:52
@tirumaraiselvan Thanks for the suggestion! 

Yes, I think `oneOf` could become a union type. It may be difficult to determine good names for the different types in the union, especially if the OAS does not store the schemas in `components` and makes use of references. Another problem is determining the correct type if the returned data is ambiguous (all we can do is compare the properties of the schemas and data although we can also expose this and offload the responsibility to the user). 

***

I think `anyOf` could be an interface type, if you mean trying to extract the common fields among all the schemas, but I think this approach has very limited usefulness. We would have to move the additional fields elsewhere... perhaps in a [GraphQL JSON](https://github.com/taion/graphql-type-json) type but this would change the structure of the data which is not good. 

Arguably, combining all the schemas (like how we resolve `allOf`) is more useful as the user would be able to query all of the fields and the type would be able to borrow links from individual schemas and allow for nesting.

**Comment by tirumaraiselvan** [comment] 2019-07-12 16:09
Right. I understand the issues better now :)

So what are your thoughts?

**Comment by Alan-Cha** [comment] 2019-07-12 17:34
I think for now, we will try to resolve `anyOf` like how we resolve `allOf`. We need to let the user know if combining the schemas will create logical impossibilities (e.g. if a shared property in two schemas have the different types). 

We can still have anyOf implement some kind of interface type. That could be interesting.

**Comment by tirumaraiselvan** [comment] 2019-07-15 12:08
@Alan-Cha For the time being, is there a way to modify the OAS so that we can remove `anyOf` in a safe way and yet not lose any functionality?

**Comment by ErikWittern** [comment] 2019-07-15 13:25
@tirumaraiselvan I assume that is dependent on the design of the REST API. I.e., maybe it is possible to convert currently one endpoint returning one of multiple possible responses into multiple endpoints returning a specific response each. Alternatively, if you are unable to change the API that way, you could try to create a single JSON schema in the OAS describing a superset of the possible responses. I assume that quite a few properties in it would be marked "optional". The implications for the resulting GraphQL wrapper would be that, depending on the returned response, some field values would be `null`.

**Comment by Alan-Cha** [comment] 2019-07-15 14:25
@tirumaraiselvan Yes, as @ErikWittern has said, one way to move forward is to "resolve" the `anyOf` (and `oneOf`) by creating a superset of the possible responses. There could be potential conflicts in the process but for now, this is the recommended way to deal with this issue until a new version is fully realized.

**Comment by Disturbing** [comment] 2019-07-22 07:05
Out of curiosity, and possible way to get this done this week? We're going to start implementing stripe and would miss our feature release cycle we're to get this piece later than Friday EOD PT.

No rush, just maybe a good collaboration to get it up and running in production in Aug with a big story to tell & share accross the Kinto & Hasura communities.

**Comment by ErikWittern** [comment] 2019-07-22 14:48
@Disturbing We like the idea of collaborating on this! We did not have time to look into this so far, however, and likely won't this week. Have you also started to look into how to solve this?

**Comment by Disturbing** [comment] 2019-07-22 23:23
We have not. We are looking into how to implement it as a solution on top
of Hasura.

AnyOf could be a jsonB type on hasura, but guessing that type is not a
graphql standard.

Team won’t have bandwidth on solving with our SaaS deadline around the
corner. But open to contribute in the future when bandwidth opens up.

**Comment by Kyle1668** [comment] 2019-08-08 20:42
When I encountered this issue I decided to create a new schema whose properties are the union of the properties in the `anyOf` array. While not ideal, this allowed me to move forward in situations where I was using a third-party API.

**Comment by pktippa** [comment] 2019-09-11 06:04
I am facing a similar issue with working on enabling graphql for [LoopBack 4](https://github.com/strongloop/loopback-next) example todo application.

```
OpenAPI-to-GraphQL creation event error:  OpenAPI-to-GraphQL currently 
cannot handle 'not' keyword in '{"title":"TodoExcluding[id]","not":{"anyOf":[{"required":
["id"]}]},"properties":{"title":{"type":"string"},"desc":{"type":"string"},"isComplete":
{"type":"boolean"},"remindAtAddress":{"type":"string"},"remindAtGeo":{"type":"string"}},"required":
["title"]}'

(node:18548) UnhandledPromiseRejectionWarning: AssertionError: component name invalid
```

**Comment by Alan-Cha** [comment] 2019-09-11 06:07
@pktippa I am currently working on a PR #232 that will hopefully be able to address this issue. I plan on checking it in tomorrow and creating a new release. For the time being, you can try to remove the `not` property in the OAS.

**Comment by ceefour** [comment] 2019-09-19 04:51
@Alan-Cha Got a similar issue with @pktippa :

```
d:\project_amanah\S3\quakezone\quakezone-lb>npx openapi-to-graphql http://localhost:3001/openapi.json

OpenAPI-to-GraphQL creation event error:  OpenAPI-to-GraphQL currently cannot handle 'not' keyword in '
```
```json{"title":"NewQuake","not":{"anyOf":[{"required":["id"]}]},"properties":{"name":{"type":"string"},"usgsId":{"type":"string","nullable":true},"usgsName":{"type":"string","nullable":true},"originTime":{"type":"string","format":"date-time","nullable":true},"usgsOriginTime":{"type":"string","format":"date-time","nullable":true},"irisOriginTime":{"type":"string","format":"date-time","nullable":true},"noaaLocation":{"type":"string","nullable":true},"noviantyRuptureDuration":{"type":"number","nullable":true},"noviantyPWaveDominantPeriod":{"type":"number","nullable":true},"noviantyT0xtd":{"type":"number","nullable":true},"noviantyMw":{"type":"number","nullable":true},"mw":{"type":"number","nullable":true},"usgsMw":{"type":"number","nullable":true},"irisMw":{"type":"number","nullable":true},"noaaTsunamiId":{"type":"number","nullable":true},"unknown1":{"type":"number","nullable":true},"usgsDepth":{"type":"number","nullable":true},"collectionName":{"type":"string","nullable":true},"collectionPos":{"type":"number","nullable":true},"usgsEpicenter":{"type":"string","nullable":true},"noaaTsunami":{"type":"boolean","nullable":true}},"required":["name"]}
```
```
'
```

Since this is a (IMHO) relatively simple LB4 new project, I wonder how could my simple project trigger this bug, and what is the workaround?

**Comment by Alan-Cha** [comment] 2019-09-19 15:33
@ceefour Thank you for including the resources. This is greatly appreciated. 

Unfortunately, this is still a work in progress. I've been working on a solution here and there for a while now but it is still incomplete. These schema combining keywords provide a lot of flexibility for JSON schema but is very troublesome to deal with in GraphQL. I have most of the components I need in working order but to create a more complete solution that can resolve most cases will still take more time. 

I will try to create a patch that will allow OtG to fail more gracefully (perhaps just skipping operations or return a JSON scalar type, see #248) but for the time being, the workaround is to save the OAS, to remove all instances of `not` in the OAS (this keyword does not have any meaning in GraphQL) and to replace `anyOf` and `oneOf` with `anyOf` (which might create conflicts in and of itself). 

If anyone would like to help me work on this problem, that would be lovely!

**Comment by RodrigoCS** [comment] 2019-09-30 07:37
@pktippa @ceefour 
I'm having the same issue for a freshly started loopback4 project, it seems like the openapi generator does this for the model ids.

`"not": {
"anyOf": [
{
"required": [
"id"
]
}
]
},`
If you're still interested what you can do is copy your openapi.json to a new file called something like openapi2.json in your public folder, and just remove the not: { anyOf }... part for the models id, this would allow you to start the graphql api while we wait for a better solution

**Comment by Alan-Cha** [comment] 2019-10-03 19:56
Hey everyone, first of all, I just wanted to sincerely apologize for keeping you all waiting, making promises that I could not follow through. I honestly feel very bad about it. 

I've tried multiple times to support this feature but every time, my solution was not comprehensive enough or I would underestimate the complexity of this problem. I also had an influx of other work and could not keep focus all my energy on this issue. 

Excuses aside, I've made a small patch release (version 1.6.1) that would prevent OtG from throwing an error. Honestly, this is the way it should have been from the beginning. 

We still **do not** support `anyOf`, `oneOf`, and `not`; it is a work in progress. At least, for now, we should still produce something. 

Please update your packages and let me know if the generation still works or if there are any other significant problems that I need to look into. 

***

If you would like to help out, please reach out! We're always looking for new contributors and maintainers. Even if all you can do is talk, I would love any advice on resolving this problem and any others in the future.

**Comment by tirumaraiselvan** [comment] 2019-10-08 01:19
@Alan-Cha First, thanks for your work here! 

> $ openapi-to-graphql -V
1.6.1

> $ openapi-to-graphql https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json
(node:91498) ExperimentalWarning: The http2 module is an experimental API.
OpenAPI-to-GraphQL creation event error:  Cannot process schema '{"anyOf":[{"maxLength":5000,"type":"string"},{"$ref":"#/components/schemas/account"}],"description":"The account this card belongs to. This attribute will not be in the card object if the card belongs to a customer or recipient instead.","nullable":true,"x-expansionResources":{"oneOf":[{"$ref":"#/components/schemas/account"}]}}'. Cannot identify type of schema.


Is this intended behaviour? Am I doing something wrong?

**Comment by Alan-Cha** [comment] 2020-01-28 21:15
Hey everyone! I know this has been a very, very long awaited feature but it is finally out. We have support for `allOf`, `anyOf`, `oneOf`, and `not` as well as more robust fallback mechanisms and we can officially say that we can wrap the Stripe API in GraphQL with the release of OtG v2.0.0!

In the screenshot, you can see that we are able to successfully run a query against the Stripe API. 

![Stripe_GraphQL](https://user-images.githubusercontent.com/14318081/73305851-f9f4a780-41e8-11ea-8686-efdf0cae2b29.png)

Let me know what your experience is! Thanks for sticking around!

**Closed by Alan-Cha** 2020-01-28 21:15 UTC

**Comment by ronanamsterdam** [comment] 2020-01-29 01:45
thanks a lot @Alan-Cha! and congrats on solving it 👍 
fyi @Disturbing
